### ISSUE TITLE
URL of lastest Factbook JSON is not consistent

### ISSUE THREAD

**Issue by noahbkim** [iancoleman/cia_world_factbook_api#11]
The application I'm working on requires the JSON version of the Factbook to be pulled down programmatically, Would it be possible to compile the Factbook to the same path every time and offer some other indication of when it was last updated, such as a key in the top level dictionary?

**Comment by noahbkim** [comment]
Whoops, I see that the date compiled is in the metadata. If you could just consider making the URL permanent, it would be much appreciated!

**Comment by iancoleman** [comment]
I've changed the data filename so the latest data will always be at https://github.com/iancoleman/cia_world_factbook_api/raw/master/data/factbook.json

Thanks for the feedback.
