### ISSUE TITLE
Mega link to Html Archives is gone

### ISSUE THREAD

**Issue by commoditystream** [iancoleman/cia_world_factbook_api#13]
Hi man thanks for this repo. Is there anyway i can get those mega links to html archives back.

**Comment by iancoleman** [comment]
Thanks for pointing this out. I'll update it when I get a chance, been getting slammed lately but hopefully will get to it soon. Thanks again.

**Comment by iancoleman** [comment]
Links have been updated in the readme.

See https://github.com/iancoleman/cia_world_factbook_api/commit/c1e83acf9e35adf29d73c1145b24835ec159cb5e for the change.
