### ISSUE TITLE
docs: goquery folder is missing in github.com/PuerkitoBio/

### ISSUE THREAD

**Issue by ypuzikov** [iancoleman/cia_world_factbook_api#15]
**Ack**: Have not yet managed to run the project, but seems like a very useful one, thank you for your effort!

**Issue**: When running the `go run parse_html_to_json.go` command, got an error saying that there are no go files in `github.com/PuerkitoBio/goquery`, probably because the folder is empty.
Later realised that the folder icon has an arrow pointing to the left and the folder path suggests that it is a link to a repo from someone else. 

**Suggestion**: Maybe update the readme file like "clone the goquery repo under `github.com/PuerkitoBio/`"?

**Comment by iancoleman** [comment]
Thanks for this, it had been added as a submodule instead of the files included directly.

Fixed in https://github.com/iancoleman/cia_world_factbook_api/commit/71a6302f291a4dea7c842fee263cd0b52d8df310

Thanks again for reporting this.
