### ISSUE TITLE
Compatibility with updated site structure

### ISSUE THREAD

**Issue by Robp773** [iancoleman/cia_world_factbook_api#21]
Do these scripts still work with updated world factbook site? I noticed there hasnt been an updated JSON file in a while but wanted to confirm before trying to run this myself.

**Comment by viviendracon** [comment]
They no longer work. I was using the data for a project and was unable to update. I did take the inspiration and run with it. Newest Factbook output is here. Hope it helps. https://github.com/viviendracon/cia-world-factbook

**Comment by iancoleman** [comment]
The scripts haven't been updated for the new redesign of the factbook. I haven't had time to get it done, but plan one day to do it.

The factbook pages are all being added to archive.org fairly regularly so once the parser is updated the full history will be available again, but I can't say for sure when I'll get to updating the parser.

**Comment by Robp773** [comment]
> They no longer work. I was using the data for a project and was unable to update. I did take the inspiration and run with it. Newest Factbook output is here. Hope it helps. https://github.com/viviendracon/cia-world-factbook

great thanks! I'll check that out

**Comment by Robp773** [comment]
> The scripts haven't been updated for the new redesign of the factbook. I haven't had time to get it done, but plan one day to do it.
> 
> The factbook pages are all being added to archive.org fairly regularly so once the parser is updated the full history will be available again, but I can't say for sure when I'll get to updating the parser.

ok sounds good - thanks for creating this in the first place!
